HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls')),
    path('', TemplateView.as_view(template_name="index.html"))
]

rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('form', views.form, name='form'),
    path('create', views.create, name='create')
]

rides/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64, default="")
  email = models.CharField(max_length=64, default="")
  vehicle_make = models.CharField(max_length=64, default="")
  vehicle_model = models.CharField(max_length=64, default="")
  vehicle_color = models.CharField(max_length=64, default="")
  origination = models.CharField(max_length=64)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  date = models.DateField()
  time = models.TimeField()
  taking_passengers = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)

rides/forms.py
from django import forms
from .models import Person


class RideForm(forms.Form):
  stateSearch = forms.CharField(label='Search term', max_length=64, required=False)


class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person
    exclude = []

rides/views.py
from .forms import RideForm, NewRideForm


from django.shortcuts import render, redirect

from .models import Person

# relative import of forms
# from .forms import RideForm

# Create your views here.


def index(request):

  context = {}
  context["form"] = RideForm()


  if "stateSearch" in request.GET:
    context["inputExists"] = True
    stateSearch = request.GET["stateSearch"]
    citySearch = ""

    if "citySearch" in request.GET:
      citySearch = request.GET["citySearch"]
    
    # Do we need to swap "icontains" with "startswith" ?
    context["people"] = Person.objects.filter(destination_city__icontains=citySearch, destination_state__icontains=stateSearch) | Person.objects.filter(origination__icontains=citySearch, destination_state__icontains=stateSearch)

  return render(request, "index_view.html", context)

def about(request):
    return render(request, "about.html")

def create(request):
  if request.method == "POST":
    new_ride = NewRideForm(request.POST)
    new_ride.save()
    return redirect("/rides")

def form(request):
  context = {}
  context["form"] = RideForm()
  context["new_ride_form"] = NewRideForm()
  return render(request, "form.html", context)

rides/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="d-flex mt-4">
  <div class="col-3">

  </div>

  <div class="col-6">
    <img src="{% static 'shrey_headshot.jpg' %}" alt="Image of logo" height="390" class="rounded-circle">
    <div class="m-4 fw-bold h1 custom-primary-text">Shrey Addagatla</div>
    
    <div class="m-5 h4 fw-normal">
      Shrey graduated from Princeton University with a degree in Operations Research and Financial Engineering. Outside of developing commutewith.us, he is known for being a previous member of the PayPal mafia. He, along with Peter Thiel, were among early investors in Meta (formerly Facebook). Now, he is recognized for his work in autonomous vehicle networks, specifically the development of cooperative autonomous vehicles.
    </div>
    
    <img src="{% static 'roosevelt_headshot.jpg' %}" alt="Image of logo" height="390" class="rounded-circle">
    
    <div class="m-4 fw-bold h1 custom-primary-text">Roosevelt Scaggs</div>
    
    <div class="m-5 h4 fw-normal">
      Roosevelt graduated from Princeton University with a degree in Computer Science. He has previously worked as an IT consultant for Fortune 500 companies such as Walmart, Amazon, and Apple. Currently, he has retired from consulting and is now working as a visiting professor at Yale University in the Information Technology and Management department.
    </div>
    
  </div>

  <div class="col-3">

  </div>
</div>
{% endblock %} 

rides/templates/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div>
    <!-- <form action="{% url 'rides:create' %}" method="post">
        {% csrf_token %}
        {{ new_ride_form }}
        <input type="submit" value="Submit">
      </form> -->
      <div class="d-flex">
        <div class="col-2">
            <div>
                <a href="https://www.mcdonalds.com" target="_blank" rel="noopener noreferrer"><img src="{% static 'mcdonalds.jpg' %}" width="200"></a>
              </div>
        </div>

        <div class="col-6" style="margin-left: auto; margin-right: auto;">
            <form action="{% url 'rides:create' %}" method="post">
                {% csrf_token %}
                <div class="mb-3"><label for="first_name">First Name</label><input class="form-control" name="first_name" maxlength="64" id="id_first_name" type="text"></div>
                <div class="mb-3"><label for="last_name">Last Name</label><input class="form-control" name="last_name" maxlength="64" id="id_last_name" type="text"></div>
                <div class="mb-3"><label for="email_address">Email address</label><input class="form-control" name="email" id="id_email" type="text" placeholder="name@example.com"></div>
                <div class="mb-3"><label for="vehicle_make">Vehicle Make</label><input class="form-control" name="vehicle_make" maxlength="64" id="id_vehicle_make" type="text"></div>
                <div class="mb-3"><label for="vehicle_model">Vehicle Model</label><input class="form-control" name="vehicle_model" maxlength="64" id="id_vehicle_model" type="text"></div>
                <div class="mb-3"><label for="vehicle_color">Vehicle Color</label><input class="form-control" name="vehicle_color" maxlength="64" id="id_vehicle_color" type="text"></div>
                <div class="mb-3"><label for="origination">Origination</label><input class="form-control" name="origination" maxlength="64" id="id_origination" type="text"></div>
                <div class="mb-3"><label for="destination_city">Destination City</label><input class="form-control" name="destination_city" maxlength="64" id="id_destination_city" type="text"></div>
                <div class="mb-3">
                    <label for="destination_state">Destination State</label><select class="form-control" name="destination_state" id="id_destination_state">
                        <option>AK</option>
                        <option>AZ</option>
                        <option>AR</option>
                        <option>CA</option>
                        <option>CO</option>
                        <option>CT</option>
                        <option>DE</option>
                        <option>FL</option>
                        <option>GA</option>
                        <option>HI</option>
                        <option>ID</option>
                        <option>IL</option>
                        <option>IN</option>
                        <option>IA</option>
                        <option>KS</option>
                        <option>KY</option>
                        <option>LA</option>
                        <option>ME</option>
                        <option>MD</option>
                        <option>MA</option>
                        <option>MI</option>
                        <option>MN</option>
                        <option>MS</option>
                        <option>MO</option>
                        <option>MT</option>
                        <option>NE</option>
                        <option>NV</option>
                        <option>NH</option>
                        <option>NJ</option>
                        <option>NM</option>
                        <option>NY</option>
                        <option>NC</option>
                        <option>ND</option>
                        <option>OH</option>
                        <option>OK</option>
                        <option>OR</option>
                        <option>PA</option>
                        <option>RI</option>
                        <option>SC</option>
                        <option>SD</option>
                        <option>TN</option>
                        <option>TX</option>
                        <option>UT</option>
                        <option>VT</option>
                        <option>VA</option>
                        <option>WA</option>
                        <option>WV</option>
                        <option>WI</option>
                        <option>WY</option>
                    </select>
                </div>
                <div class="mb-3"><label for="date">Date</label><input class="form-control" name="date" id="id_date" type="text" placeholder="01/01/2022"></div>
                <div class="mb-3"><label for="time">Time</label><input class="form-control" name="time" id="id_time" type="text" placeholder="14:30"></div>
                <div class="form-check mb-3">
                    <input class="form-check-input" name="taking_passengers" id="id_taking_passengers" type="checkbox" onclick="checkSeats()">
                    <label class="form-check-label" for="flexCheckDefault">Taking Passengers?</label>
                </div>
                <div class="mb-3"><label for="seats_available">Seats Available</label><input class="form-control" name="seats_available" id="id_seats_available" type="number" value=1></div>
                <input type="submit" class="btn btn-primary p-3" value="Submit">
            </form>
        </div>

        <div class="col-2">
            <div>
                <a href="http://www.luciopizza.com" target="_blank" rel="noopener noreferrer"><img src="{% static 'lucios-pizza.png' %}"></a>
              </div>
        </div>
        </div>
      <br>
{% endblock %}

rides/templates/index_view.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<form class="m-3" action="{% url 'rides:index' %}" method="get">
    {{ form }}
    <input type="submit" value="Submit" onclick="return checkForm()">
</form>

<div class="main">
  <div class="d-flex">
    <div class="col-2">
      <div>
        <a href="https://www.mcdonalds.com" target="_blank" rel="noopener noreferrer"><img src="{% static 'mcdonalds.jpg' %}" width="200"></a>
      </div>
    </div>
    
    <div class="col-8">
      {% if inputExists %}
    <table id="example" class="table table-striped table-bordered m-4">
      <thead class="bg-primary text-white">
          <tr>
              <th>First Name</th>
              <th>Origination</th>
              <th>Destination</th>
              <th>State</th>
              <th>Date</th>
              <th>Time</th>
              <th>Taking Passenegers?</th>
              <th>Seats Available</th>
          </tr>
      </thead>
      <tbody>
          {% for person in people %}
        <tr>
            <td>{{ person.first_name }}</td> 
            <td>{{ person.origination }}</td>
            <td>{{ person.destination_city }}</td> 
            <td>{{ person.destination_state }}</td> 
            <td>{{ person.date }}</td> 
            <td>{{ person.time }}</td> 
            <td>{{ person.taking_passengers }}</td>
            <td>{{ person.seats_available }}</td> 
        </tr>
        {% endfor %} 
      </tbody>
    </table>
    {% endif %}
    </div>

    <div class="col-2">
      <div>
        <a href="http://www.luciopizza.com" target="_blank" rel="noopener noreferrer"><img src="{% static 'lucios-pizza.png' %}"></a>
      </div>
    </div>
  </div>  
  </div>

{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
  <title> ORF 401: Spring 2020 </title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css" rel="stylesheet" />
  
  <link href="{% static 'styles.css' %}" rel="stylesheet">
  <link href="{% static 'main.css' %}" rel="stylesheet">
  <script src="{% static 'main.js' %}"></script>
</head>
  <body text="black">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <a class="navbar-brand" href="/rides"><img src="{% static 'logo-long.png' %}" alt="Image of logo" width="200"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/rides/about">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/rides/form">Create Ride</a>
          </li>
        </ul>
      </div>
    </nav>
    <div role="presentation" class="bg-lightGrey mb-3">
      <article class="">
        <div class="">
          <span class="">
            <span class="">
              <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="" width="24" height="24" aria-hidden="true">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-337.000000, -417.000000)"><g transform="translate(336.000000, 416.000000)">
                  <g>
                    <path d="M12,22.0652174 C6.44113393,22.0652174 1.93478261,17.5588661 1.93478261,12 C1.93478261,6.44113393 6.44113393,1.93478261 12,1.93478261 C17.5588661,1.93478261 22.0652174,6.44113393 22.0652174,12 C22.0652174,17.5588661 17.5588661,22.0652174 12,22.0652174 Z M12,21.0652174 C17.0065813,21.0652174 21.0652174,17.0065813 21.0652174,12 C21.0652174,6.99341868 17.0065813,2.93478261 12,2.93478261 C6.99341868,2.93478261 2.93478261,6.99341868 2.93478261,12 C2.93478261,17.0065813 6.99341868,21.0652174 12,21.0652174 Z" fill="#708C91" fill-rule="nonzero"></path>
                    <path d="M11.5,7.65217391 C11.5,7.37603154 11.7238576,7.15217391 12,7.15217391 C12.2761424,7.15217391 12.5,7.37603154 12.5,7.65217391 L12.5,12.8695652 C12.5,13.1457076 12.2761424,13.3695652 12,13.3695652 C11.7238576,13.3695652 11.5,13.1457076 11.5,12.8695652 L11.5,7.65217391 Z" fill="#708C91" fill-rule="nonzero"></path>
                    <circle fill="#708C91" fill-rule="nonzero" cx="12" cy="16.3478261" r="1"></circle>
                  </g></g></g></g>
                </svg>
              </span>
              <span class="kirk-item-leftText"><span class="kirk-text kirk-text-title sc-faUpoM gHhpVx" style="color: rgb(112, 140, 145);">COVID-19: read more about recommended precautions on the <a href="https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/index.html">CDC Website</a>
              </span>
            </span>
          </span>
        </div>
      </article>
    </div>
      {% block content %}
      {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% load static %}
<html>
<head>
  <title> ORF 401: Spring 2020 </title>
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
  <link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link href="{% static 'main.css' %}" rel="stylesheet">
  <script src="{% static 'main.js' %}"></script>
</head>
  <body text="black" onload="checkCookie()">
    <div class="d-flex mt-4">
      <div class="col-3">

      </div>

      <div class="col-6 align-items-center">
        <a href="/rides"><img src="{% static 'logo-long.png' %}" alt="Image of logo" width="900"></a>
        
        <div class="m-4 fw-bold h1 custom-primary-text">Welcome to commutewith.us!</div>
        
        <div class="m-4 h4 fw-normal">
          Our goal is to connect people to casually share rides. That is, we want you to find others with enough in common so that you're comfortable sharing a ride with each other. 
          Many event goers could share rides if only they knew that someone near them was attending too, and with commutewith.us, you can do just that! 
          Below, you'll be able to navigate to our homepage, so you can make your first search!
        </div>
        <a href="/rides"><button type="button" class="btn btn-lg btn-custom-primary">Enter</button></a>
      </div>

      <div class="col-3">

      </div>
    </div>
    
  </body>
</html>